#!/usr/bin/env zsh

JOURNAL_DIR="$HOME/journal/$(date +%Y/%m)"
TODAY=$(date +%Y-%m-%d)
FILE="$JOURNAL_DIR/$TODAY.md"

if ! [[ -f $FILE ]]; then
    echo "could not find file: $FILE"
    exit 1
fi

clear
glow $FILE

