#!/usr/bin/env zsh
source ~/.zshaliases

NOTES_DIR="$HOME/notes/$(date +%Y/%m)"
TODAY=$(date +%Y-%m-%d)
FILE="$NOTES_DIR/$TODAY.md"

if [ ! -f $FILE ]; then
	echo "could not find file: $FILE"
	exit 1
fi

clear
watchglow $FILE
