filetype on
filetype plugin on
set tabstop=4
set shiftwidth=4
set expandtab
autocmd FileType make set tabstop=8 shiftwidth=8 softtabstop=0 noexpandtab
autocmd FileType haskell set tabstop=2 shiftwidth=2
autocmd FileType sml set tabstop=2 shiftwidth=2
syntax on
set number
set colorcolumn=81

