filetype on
filetype plugin indent on    " required
set tabstop=4
set shiftwidth=4
set expandtab
autocmd FileType make set tabstop=8 shiftwidth=8 softtabstop=0 noexpandtab
autocmd FileType haskell set tabstop=2 shiftwidth=2
autocmd FileType sml set tabstop=2 shiftwidth=2
syntax on
set number
set colorcolumn=81

" Write current buffer if changed before navigating from Vim to tmux pane
let g:tmux_navigator_save_on_switch = 1

set rtp+=/opt/homebrew/opt/fzf
