""""""""" Custom settings
set shell=zsh
set tabstop=4
set shiftwidth=4
set expandtab
set smartcase
autocmd FileType make set tabstop=8 shiftwidth=8 softtabstop=0 noexpandtab
autocmd FileType haskell set tabstop=2 shiftwidth=2
autocmd FileType sml set tabstop=2 shiftwidth=2
syntax on
set number
set colorcolumn=81
set belloff=all
set termguicolors
" Write current buffer if changed before navigating from Vim to tmux pane
let g:tmux_navigator_save_on_switch = 1

"" Plugin settings
nnoremap <C-p> :NERDTreeToggle<CR>

" Indentation mappings
nmap >> <Nop>
nmap << <Nop>
vmap >> <Nop>
vmap << <Nop>
nnoremap <Tab>   >>
nnoremap <S-Tab> <<
vnoremap <Tab>   >><Esc>gv
vnoremap <S-Tab> <<<Esc>gv

" Ctr-/ shortcut for comment-out mapping
nmap <C-_> gcc
vmap <C-_> gc<Esc>gv

" Python highlighting
let g:python_highlight_space_errors = 0
let g:python_version_2 = 0
let g:python_highlight_all = 1

" Airline
let g:airline_theme='term'
let g:airline_detect_paste = 1
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'

" vimtex
let g:tex_flavor='latex'
let g:vimtex_view_method='skim'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'
let g:vimtex_compiler_latexmk = {
    \ 'aux_dir' : '',
    \ 'out_dir' : '',
    \ 'callback' : 1,
    \ 'continuous' : 1,
    \ 'executable' : 'latexmk',
    \ 'hooks' : [],
    \ 'options' : [
    \   '-verbose',
    \   '-file-line-error',
    \   '-synctex=1',
    \   '-interaction=nonstopmode',
    \   '--shell-escape',
    \ ],
    \}
" let g:vimtex_quickfix_ignore_filters = [
"       \ 'Underfull \\hbox',
"       \ 'Overfull \\hbox',
"       \]

" snippets
let g:UltiSnipsExpandTrigger = '<C-e>'
let g:UltiSnipsJumpForwardTrigger = '<C-w>'
let g:UltiSnipsJumpBackwardTrigger = '<C-q>'
let g:UltiSnipsSnippetDirectories = ["UltiSnips", "snippets-custom"]

set rtp+=/opt/homebrew/opt/fzf

" Trimming whitespace shortcut
function! Trim()
    let l:save = winsaveview()
    keeppatterns %s/\s\+$//e
    call winrestview(l:save)
endfunction
nnoremap <C-s> :call Trim()<CR>

""""" required for Vundle setup:
set nocompatible
set encoding=UTF-8
filetype on
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

""" User plugins go here:
Plugin 'catppuccin/vim', { 'as': 'catppuccin' }
Plugin 'valloric/youcompleteme'
" YCM docs: https://github.com/ycm-core/YouCompleteMe?tab=readme-ov-file
Plugin 'sheerun/vim-polyglot'
Plugin 'scrooloose/nerdtree'
Plugin 'sirver/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'tpope/vim-surround'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'lervag/vimtex'
Plugin 'tiagofumo/vim-nerdtree-syntax-highlight'
Plugin 'tpope/vim-commentary'
Plugin 'ryanoasis/vim-devicons' " should be last plugin

call vundle#end()            " required
filetype plugin indent on    " required

