#!/bin/zsh
HW=$1
CNET=$2
mv ~/Downloads/$HW-$CNET.rkt ~/CMSC/g-cs151-s22/$HW/$HW-$CNET.rkt
cat ~/CMSC/g-cs151-s22/$HW/tests-$HW.txt >> ~/CMSC/g-cs151-s22/$HW/$HW-$CNET.rkt
echo $CNET >> ~/CMSC/g-cs151-s22/$HW/students.txt
