#!/bin/bash
sudo python3 $STORAGE_PATH/CMSC/cs-tools/tools/refind-next-boot.py 'Microsoft'
echo "Would you like to reboot to Windows? (y/n): "
read response

if [ $response == "y" ]
then
sudo reboot now
else
echo "Reboot cancelled."
exit
fi